package com.evh98.hydrogen.util;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.Texture.TextureFilter;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.evh98.hydrogen.Hydrogen;

public class Assets {
	
	public static Texture Tblock;
	public static TextureRegion block;
	public static Texture Thealth1;
	public static TextureRegion health1;
	public static Texture Thealth2;
	public static TextureRegion health2;
	public static Texture Thealth3;
	public static TextureRegion health3;
	public static Texture Thealth4;
	public static TextureRegion health4;
	public static Texture Thealth5;
	public static TextureRegion health5;
	public static Texture Thealth6;
	public static TextureRegion health6;
	public static Texture Thealth7;
	public static TextureRegion health7;
	public static Texture Thealth8;
	public static TextureRegion health8;
	public static Texture Thealth9;
	public static TextureRegion health9;
	public static Texture Thealth10;
	public static TextureRegion health10;
	public static Texture Tmain;
	public static TextureRegion main;
	public static Texture Tpoint;
	public static TextureRegion point;
	public static Texture Tpoison;
	public static TextureRegion poison;
	public static Texture Tregen;
	public static TextureRegion regen;
	public static Texture Tback;
	public static TextureRegion back;
	public static Texture Tmore;
	public static TextureRegion more;
	public static Texture Thelp;
	public static TextureRegion help;
	public static Texture Tend;
	public static TextureRegion end;
	
	public static Texture Tmain_exit;
	public static TextureRegion main_exit;
	public static Texture Tmain_facebook;
	public static TextureRegion main_facebook;
	public static Texture Tmain_help;
	public static TextureRegion main_help;
	public static Texture Tmain_more;
	public static TextureRegion main_more;
	public static Texture Tmain_play;
	public static TextureRegion main_play;
	public static Texture Tmain_twitter;
	public static TextureRegion main_twitter;
	
	public static Texture Tdiff_easy;
	public static TextureRegion diff_easy;
	public static Texture Tdiff_medium;
	public static TextureRegion diff_medium;
	public static Texture Tdiff_hard;
	public static TextureRegion diff_hard;
	public static Texture Tdiff_harder;
	public static TextureRegion diff_harder;
	
	public static Texture Tpause_back;
	public static TextureRegion pause_back;
	public static Texture Tpause_continue;
	public static TextureRegion pause_continue;
	public static Texture Tpause_menu;
	public static TextureRegion pause_menu;
	public static Texture Tpause_sound_off;
	public static TextureRegion pause_sound_off;
	public static Texture Tpause_sound_on;
	public static TextureRegion pause_sound_on;
	public static TextureRegion pause_sound;
	
	public static Sound click;
	public static Sound negative;
	public static Sound positive;
	
	public static void load(){
		Hydrogen.sound = true;
		
		Tblock = new Texture(Gdx.files.internal("game/block.png"));
		Tblock.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		block = new TextureRegion(Tblock);
		block.flip(false, true);
		Thealth1 = new Texture(Gdx.files.internal("game/health1.png"));
		Thealth1.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health1 = new TextureRegion(Thealth1);
		health1.flip(false, true);
		Thealth2 = new Texture(Gdx.files.internal("game/health2.png"));
		Thealth2.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health2 = new TextureRegion(Thealth2);
		health2.flip(false, true);
		Thealth3 = new Texture(Gdx.files.internal("game/health3.png"));
		Thealth3.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health3 = new TextureRegion(Thealth3);
		health3.flip(false, true);
		Thealth4 = new Texture(Gdx.files.internal("game/health4.png"));
		Thealth4.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health4 = new TextureRegion(Thealth4);
		health4.flip(false, true);
		Thealth5 = new Texture(Gdx.files.internal("game/health5.png"));
		Thealth5.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health5 = new TextureRegion(Thealth5);
		health5.flip(false, true);
		Thealth6 = new Texture(Gdx.files.internal("game/health6.png"));
		Thealth6.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health6 = new TextureRegion(Thealth6);
		health6.flip(false, true);
		Thealth7 = new Texture(Gdx.files.internal("game/health7.png"));
		Thealth7.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health7 = new TextureRegion(Thealth7);
		health7.flip(false, true);
		Thealth8 = new Texture(Gdx.files.internal("game/health8.png"));
		Thealth8.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health8 = new TextureRegion(Thealth8);
		health8.flip(false, true);
		Thealth9 = new Texture(Gdx.files.internal("game/health9.png"));
		Thealth9.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health9 = new TextureRegion(Thealth9);
		health9.flip(false, true);
		Thealth10 = new Texture(Gdx.files.internal("game/health10.png"));
		Thealth10.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		health10 = new TextureRegion(Thealth10);
		health10.flip(false, true);
		Tmain = new Texture(Gdx.files.internal("game/main.png"));
		Tmain.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		main = new TextureRegion(Tmain);
		main.flip(false, true);
		Tpoint = new Texture(Gdx.files.internal("game/point.png"));
		Tpoint.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		point = new TextureRegion(Tpoint);
		point.flip(false, true);
		Tpoison = new Texture(Gdx.files.internal("game/poison.png"));
		Tpoison.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		poison = new TextureRegion(Tpoison);
		poison.flip(false, true);
		Tregen = new Texture(Gdx.files.internal("game/regen.png"));
		Tregen.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		regen = new TextureRegion(Tregen);
		regen.flip(false, true);
		Tback = new Texture(Gdx.files.internal("game/back.png"));
		Tback.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		back = new TextureRegion(Tback);
		back.flip(false, true);
		Tmore = new Texture(Gdx.files.internal("more.png"));
		Tmore.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		more = new TextureRegion(Tmore);
		more.flip(false, true);
		Thelp = new Texture(Gdx.files.internal("help.png"));
		Thelp.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		help = new TextureRegion(Thelp);
		help.flip(false, true);
		Tend = new Texture(Gdx.files.internal("end.png"));
		Tend.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		end = new TextureRegion(Tend);
		end.flip(false, true);
		
		Tmain_exit = new Texture(Gdx.files.internal("main/exit.png"));
		Tmain_exit.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		main_exit = new TextureRegion(Tmain_exit);
		main_exit.flip(false, true);
		Tmain_facebook = new Texture(Gdx.files.internal("main/facebook.png"));
		Tmain_facebook.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		main_facebook = new TextureRegion(Tmain_facebook);
		main_facebook.flip(false, true);
		Tmain_help = new Texture(Gdx.files.internal("main/help.png"));
		Tmain_help.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		main_help = new TextureRegion(Tmain_help);
		main_help.flip(false, true);
		Tmain_more = new Texture(Gdx.files.internal("main/more.png"));
		Tmain_more.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		main_more = new TextureRegion(Tmain_more);
		main_more.flip(false, true);
		Tmain_play = new Texture(Gdx.files.internal("main/play.png"));
		Tmain_play.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		main_play = new TextureRegion(Tmain_play);
		main_play.flip(false, true);
		Tmain_twitter = new Texture(Gdx.files.internal("main/twitter.png"));
		Tmain_twitter.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		main_twitter = new TextureRegion(Tmain_twitter);
		main_twitter.flip(false, true);

		Tdiff_easy = new Texture(Gdx.files.internal("diff/easy.png"));
		Tdiff_easy.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		diff_easy = new TextureRegion(Tdiff_easy);
		diff_easy.flip(false, true);
		Tdiff_medium = new Texture(Gdx.files.internal("diff/medium.png"));
		Tdiff_medium.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		diff_medium = new TextureRegion(Tdiff_medium);
		diff_medium.flip(false, true);
		Tdiff_hard = new Texture(Gdx.files.internal("diff/hard.png"));
		Tdiff_hard.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		diff_hard = new TextureRegion(Tdiff_hard);
		diff_hard.flip(false, true);
		Tdiff_harder = new Texture(Gdx.files.internal("diff/harder.png"));
		Tdiff_harder.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		diff_harder = new TextureRegion(Tdiff_harder);
		diff_harder.flip(false, true);
		
		Tpause_back = new Texture(Gdx.files.internal("pause/back.png"));
		Tpause_back.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		pause_back = new TextureRegion(Tpause_back);
		pause_back.flip(false, true);
		Tpause_menu = new Texture(Gdx.files.internal("pause/menu.png"));
		Tpause_menu.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		pause_menu = new TextureRegion(Tpause_menu);
		pause_menu.flip(false, true);
		Tpause_continue = new Texture(Gdx.files.internal("pause/continue.png"));
		Tpause_continue.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		pause_continue = new TextureRegion(Tpause_continue);
		pause_continue.flip(false, true);
		Tpause_sound_off = new Texture(Gdx.files.internal("pause/sound_off.png"));
		Tpause_sound_off.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		pause_sound_off = new TextureRegion(Tpause_sound_off);
		pause_sound_off.flip(false, true);
		Tpause_sound_on = new Texture(Gdx.files.internal("pause/sound_on.png"));
		Tpause_sound_on.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		pause_sound_on = new TextureRegion(Tpause_sound_on);
		pause_sound_on.flip(false, true);
		pause_sound = pause_sound_on;
		
		click = Gdx.audio.newSound(Gdx.files.internal("sfx/click.mp3"));
		positive = Gdx.audio.newSound(Gdx.files.internal("sfx/positive.mp3"));
		negative = Gdx.audio.newSound(Gdx.files.internal("sfx/negative.mp3"));
	}
}